apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-host1
  labels:
    release: stable
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/data1
    
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-host2
  labels:
    release: stable
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/data2    
    
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-host3
  labels:
    release: stable
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/data3
