apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ APP_NAME }}-jenkins
  labels:
    app: {{ APP_NAME }}-jenkins
spec:
  template:
    metadata:
      name: {{ APP_NAME }}-jenkins
      labels:
        app: {{ APP_NAME }}-jenkins
    spec:
      containers:
      - name: {{ APP_NAME }}-jenkins
        image: daocloud.io/jenkins:latest
        ports:
        - containerPort: 8080
          name: jenkins-0
        - containerPort: 50000
          name: jenkins-1
---
apiVersion: v1
kind: Service
metadata:
  name: {{ APP_NAME }}-jenkins
spec:
  type: NodePort
  ports:
  - port: 8080
    name: jenkins-0
  - port: 50000
    name: jenkins-1
  selector:
    app: {{ APP_NAME }}-jenkins
