apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ APP_NAME }}-ghost
  labels:
    app: {{ APP_NAME }}-ghost
spec:
  template:
    metadata:
      name: {{ APP_NAME }}-ghost
      labels:
        app: {{ APP_NAME }}-ghost
    spec:
      containers:
      - name: {{ APP_NAME }}-ghost
        image: daocloud.io/ghost:latest
        ports:
        - containerPort: 2368
---
apiVersion: v1
kind: Service
metadata:
  name: {{ APP_NAME }}-ghost
spec:
  type: NodePort
  ports:
  - port: 2368
  selector:
    app: {{ APP_NAME }}-ghost
