apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ APP_NAME }}-jboss
  labels:
    app: {{ APP_NAME }}-jboss
spec:
  template:
    metadata:
      name: {{ APP_NAME }}-jboss
      labels:
        app: {{ APP_NAME }}-jboss
    spec:
      containers:
      - name: {{ APP_NAME }}-jboss
        image: daocloud.io/daocloud/jboss-wildfly
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: "0.9"
            memory: "2147483648"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ APP_NAME }}-jboss
  labels:
    app: {{ APP_NAME }}-jboss
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: {{ APP_NAME }}-jboss