---
kind: StatefulSet
apiVersion: apps/v1beta2
metadata:
  name: cluster2-hdfs-datanode
  labels:
    app: hadoop
    component: hadoop-datanode
    cluster: cluster2
  annotations:
    hadoop/version: 2.7.3
    jdk/version: jdk1.8.0_161
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hadoop
      component: hadoop-datanode
      cluster: cluster2
  template:
    metadata:
      labels:
        app: hadoop
        component: hadoop-datanode
        cluster: cluster2
    spec:
      volumes:
      - name: hdfs-config
        configMap:
          name: cluster2-hdfs-configmap
          defaultMode: 420 
      - name: rm-config
        configMap:
          name: cluster2-rm-configmap
          defaultMode: 420
      containers:
      - name: cluster2-datanode
        image: zhhray/hadoop:2.7.3
        command:
        - "/bin/bash"
        - "/etc/hadoop-config/bootstrap.sh"
        - "-d"
        env:
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: hdfs-client
          containerPort: 50010
          protocol: TCP
        - name: hdfs-ipc
          containerPort: 50020
          protocol: TCP
        - name: web-http
          containerPort: 50075
          protocol: TCP  
        - name: nm-ipc
          containerPort: 8040
          protocol: TCP   
        - name: nm-address
          containerPort: 8041
          protocol: TCP    
        - name: nm-webapp
          containerPort: 8042
          protocol: TCP   
        resources:
          limits:
            cpu: '1'
            memory: 2Gi
          requests:
            cpu: 10m
            memory: 256Mi
        volumeMounts:
        - name: hdfs-config
          mountPath: "/tmp/hadoop/hdfs"
        - name: rm-config
          mountPath: "/tmp/hadoop/resourcemanager"  
        - name: datadir
          mountPath: "/usr/local/hadoop/tmp"
        livenessProbe:
          exec:
            command:
            - "/bin/bash"
            - "/etc/hadoop-config/healthcheck-datanode.sh"
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - "/bin/bash"
            - "/etc/hadoop-config/healthcheck-datanode.sh"
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3  
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      ### podAntiAffinity 描述pod被调度的策略
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: hadoop
                  component: hadoop-datanode
                  cluster: cluster2
              topologyKey: kubernetes.io/hostname           
      schedulerName: default-scheduler
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi      
  serviceName: cluster2-datanode-headless
  podManagementPolicy: Parallel
