---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk-pv-2
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /k8s-nfs-storage/zhh/bigdata-demo-1/zkdata/zk-2
    server: 10.221.105.172
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-zookeeper-cluster-2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
