---
kind: StatefulSet
apiVersion: apps/v1beta2
metadata:
  name: zookeeper-cluster
  labels:
    app: zookeeper
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      creationTimestamp: 
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper-server
        image: zhhray/k8szk:v2
        command:
        - sh
        - "-c"
        - zkGenConfig.sh && exec zkServer.sh start-foreground
        ports:
        - name: client
          containerPort: 2181
          protocol: TCP
        - name: server
          containerPort: 2888
          protocol: TCP
        - name: leader-election
          containerPort: 3888
          protocol: TCP
        env:
        - name: ZK_REPLICAS
          value: '3'
        - name: ZK_HEAP_SIZE
          value: 2G
        - name: ZK_TICK_TIME
          value: '2000'
        - name: ZK_INIT_LIMIT
          value: '10'
        - name: ZK_SYNC_LIMIT
          value: '5'
        - name: ZK_MAX_CLIENT_CNXNS
          value: '60'
        - name: ZK_SNAP_RETAIN_COUNT
          value: '3'
        - name: ZK_PURGE_INTERVAL
          value: '1'
        - name: ZK_LOG_LEVEL
          value: INFO
        - name: ZK_CLIENT_PORT
          value: '2181'
        - name: ZK_SERVER_PORT
          value: '2888'
        - name: ZK_ELECTION_PORT
          value: '3888'
        resources:
          limits:
            cpu: '1'
            memory: 4Gi
          requests:
            cpu: 300m
            memory: 400m
        volumeMounts:
        - name: datadir
          mountPath: "/var/lib/zookeeper"
          subPath: data
        livenessProbe:
          exec:
            command:
            - zkOk.sh
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - zkOk.sh
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
  serviceName: zookeeper-headless
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: OnDelete
  revisionHistoryLimit: 10