---
kind: Service
apiVersion: v1
metadata:
  name: zookeeper-server
  labels:
    app: zookeeper
spec:
  ports:
  - name: client
    protocol: TCP
    port: 2181
    targetPort: 2181
  type: ClusterIP
  selector:
    app: zookeeper