# sudo apt-get install postgresql-client; 
# psql -h 10.221.105.132 -p 30250 -U root -W password
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: postgres
  labels:
    name: postgres
spec:
  selector:
    matchLabels:
      name: postgres
  template:
    metadata:
      labels:
        name: postgres
    spec:
      containers:
        - name: postgres
          image: 'index.tenxcloud.com/tenxcloud/postgres:9.6.1'
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: PATH
              value: >-
                /usr/lib/postgresql/9.6/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            - name: GOSU_VERSION
              value: '1.7'
            - name: LANG
              value: en_US.utf8
            - name: PG_MAJOR
              value: '9.6'
            - name: PG_VERSION
              value: 9.6.1-2.pgdg80+1
            - name: PGDATA
              value: /var/lib/postgresql/data
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: root
          command:
            - /docker-entrypoint.sh
          args:
            - postgres
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 512Mi
---
kind: Service
apiVersion: v1
metadata:
  name: postgres
  labels:
    name: postgres
  annotations:
    schemaPortname: postgres-1/TCP
spec:
  ports:
    - name: postgres-1
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    name: postgres
  type: "NodePort"  
