#psql -U postgres #passowrd
kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres
  labels:
    name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres
  template:
    metadata:
      labels:
        name: postgres
    spec:
      containers:
      - name: postgres
        image: bitnami/postgresql:10.4.0
        env:
        - name: POSTGRESQL_PASSWORD
          value: 'password'
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
          - name: postgres-data
            mountPath: /bitnami/postgresql
      volumes:
      - name: postgres-data
        emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: postgres-service
  labels:
    name: postgres
spec:
  type: NodePort
  ports:
  - protocol: TCP
    targetPort: 5432
    port: 5432
    name: port
  selector:
    name: postgres