apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ APP_NAME }}-metabase
  labels:
    app: {{ APP_NAME }}-metabase
spec:
  template:
    metadata:
      name: {{ APP_NAME }}-metabase
      labels:
        app: {{ APP_NAME }}-metabase
    spec:
      containers:
      - name: {{ APP_NAME }}-metabase
        image: daocloud.io/daocloud/metabase
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ APP_NAME }}-metabase
spec:
  type: NodePort
  ports:
  - port: 3000
  selector:
    app: {{ APP_NAME }}-metabase
