apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ APP_NAME }}-registry
  labels:
    app: {{ APP_NAME }}-registry
spec:
  template:
    metadata:
      name: {{ APP_NAME }}-registry
      labels:
        app: {{ APP_NAME }}-registry
    spec:
      containers:
      - name: {{ APP_NAME }}-registry
        image: daocloud.io/registry:2.3
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ APP_NAME }}-registry
spec:
  type: NodePort
  ports:
  - port: 5000
  selector:
    app: {{ APP_NAME }}-registry
