apiVersion: v1
kind: Service
metadata:
  name: {{ APP_NAME }}-wordpress
  labels:
    app: {{ APP_NAME }}-wordpress
spec:
  ports:
    - port: 80
  selector:
    app: {{ APP_NAME }}-wordpress
    tier: frontend
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ APP_NAME }}-wordpress
  labels:
    app: {{ APP_NAME }}-wordpress
spec:
  template:
    metadata:
      labels:
        app: {{ APP_NAME }}-wordpress
        tier: frontend
    spec:
      containers:
      - image: daocloud.io/wordpress
        name: {{ APP_NAME }}-wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: {{ APP_NAME }}-wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          value: {{ MYSQL_PASSWORD }}
        ports:
        - containerPort: 80
          name: wordpress
---
apiVersion: v1
kind: Service
metadata:
  name: {{ APP_NAME }}-wordpress-mysql
  labels:
    app: {{ APP_NAME }}-wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: {{ APP_NAME }}-wordpress
    tier: mysql
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ APP_NAME }}-wordpress-mysql
  labels:
    app: {{ APP_NAME }}-wordpress
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ APP_NAME }}-wordpress
        tier: mysql
    spec:
      containers:
      - image: daocloud.io/mysql:5.6
        name: {{ APP_NAME }}-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ MYSQL_PASSWORD }}
        ports:
        - containerPort: 3306
          name: mysql
