apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ APP_NAME }}-tomcat
  labels:
    app: {{ APP_NAME }}-tomcat
spec:
  template:
    metadata:
      name: {{ APP_NAME }}-tomcat
      labels:
        app: {{ APP_NAME }}-tomcat
    spec:
      containers:
      - name: {{ APP_NAME }}-tomcat
        image: daocloud.io/tomcat:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "0.5"
            memory: "2147483648"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ APP_NAME }}-tomcat
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: {{ APP_NAME }}-tomcat