apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ APP_NAME }}-phpmyadmin
  labels:
    app: {{ APP_NAME }}-phpmyadmin
spec:
  template:
    metadata:
      name: {{ APP_NAME }}-phpmyadmin
      labels:
        app: {{ APP_NAME }}-phpmyadmin
    spec:
      containers:
      - name: {{ APP_NAME }}-phpmyadmin
        image: daocloud.io/daocloud/phpmyadmin
        ports:
        - containerPort: 80
        env:
          - name: PMA_ARBITRARY
            value: "1"
        volumeMounts:
        - name: session
          mountPath: /sessions
      volumes:
      - name: session
        hostPath:
          path: /sessions
---
apiVersion: v1
kind: Service
metadata:
  name: {{ APP_NAME }}-phpmyadmin
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: {{ APP_NAME }}-phpmyadmin
