---
kind: StatefulSet
apiVersion: apps/v1beta2
metadata:
  name: hadoop-hdfs-resourcemanager
  labels:
    app: hadoop
    component: hadoop-resourcemanager
  annotations:
    hadoop/version: 2.7.3
    jdk/version: jdk1.8.0_161
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hadoop
      component: hadoop-resourcemanager
  template:
    metadata:
      labels:
        app: hadoop
        component: hadoop-resourcemanager
    spec:
      volumes:
      - name: hadoop-config
        configMap:
          name: hadoop-cm
          defaultMode: 420
      - name: dfs-tmp
        emptyDir: {}
      containers:
      - name: hadoop-resourcemanager
        image: zhhray/hadoop:2.7.3
        command:
        - "/bin/bash"
        - "/etc/hadoop-config/bootstrap.sh"
        - "-d"
        env:
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: manager
          containerPort: 8032
          protocol: TCP
        - name: scheduler
          containerPort: 8030
          protocol: TCP
        - name: tracker
          containerPort: 8031
          protocol: TCP 
        - name: admin
          containerPort: 8033
          protocol: TCP   
        - name: http
          containerPort: 8088
          protocol: TCP       
        resources:
          limits:
            cpu: '1'
            memory: 2Gi
          requests:
            cpu: 10m
            memory: 256Mi
        volumeMounts:
        - name: hadoop-config
          mountPath: "/tmp/hadoop"
        - name: dfs-tmp
          mountPath: "/usr/local/hadoop/tmp"
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
      dnsPolicy: ClusterFirst
      securityContext: {}
      ### podAntiAffinity 描述pod被调度的策略
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: hadoop
                  component: hadoop-resourcemanager
              topologyKey: kubernetes.io/hostname           
      schedulerName: default-scheduler
  serviceName: hadoop-resourcemanager-headless
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: OnDelete
  revisionHistoryLimit: 10
