---
kind: StatefulSet
apiVersion: apps/v1beta2
metadata:
  name: hadoop-hdfs-resourcemanager
  labels:
    app: hadoop
    component: hadoop-resourcemanager
  annotations:
    hadoop/version: 2.7.3
    jdk/version: jdk1.8.0_161
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hadoop
      component: hadoop-resourcemanager
  template:
    metadata:
      labels:
        app: hadoop
        component: hadoop-resourcemanager
    spec:
      volumes:
      - name: hdfs-config
        configMap:
          name: hdfs-configmap
          defaultMode: 420
      - name: rm-config
        configMap:
          name: resourcemanager-configmap
          defaultMode: 420    
      initContainers:
      - name: init-set-label
        command: 
          - "sh"
          - "-c"
          - "/usr/local/bin/kubectl label pod ${HOSTNAME} set-hostname=${HOSTNAME}"
        image: lachlanevenson/k8s-kubectl:v1.8.4    
      containers:
      - name: hadoop-resourcemanager
        image: zhhray/hadoop:2.7.3
        command:
        - "/bin/bash"
        - "/etc/hadoop-config/bootstrap.sh"
        - "-d"
        env:
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: manager
          containerPort: 8032
          protocol: TCP
        - name: scheduler
          containerPort: 8030
          protocol: TCP
        - name: tracker
          containerPort: 8031
          protocol: TCP 
        - name: admin
          containerPort: 8033
          protocol: TCP   
        - name: http
          containerPort: 8088
          protocol: TCP       
        resources:
          limits:
            cpu: '1'
            memory: 2Gi
          requests:
            cpu: 10m
            memory: 200Mi
        volumeMounts:
        - name: hdfs-config
          mountPath: "/tmp/hadoop/hdfs" 
        - name: rm-config
          mountPath: "/tmp/hadoop/resourcemanager"   
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      ### podAntiAffinity 描述pod被调度的策略
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: hadoop
                  component: hadoop-resourcemanager
              topologyKey: kubernetes.io/hostname           
      schedulerName: default-scheduler
  serviceName: hadoop-resourcemanager-headless
  podManagementPolicy: OrderedReady
