---
kind: Service
apiVersion: v1
metadata:
  name: hadoop-resourcemanager-master-service
  labels:
    app: hadoop
    component: hadoop-resourcemanager
spec:
  ports:
  - name: web
    protocol: TCP
    port: 8088
    targetPort: 8088
  selector:
    app: hadoop
    component: hadoop-resourcemanager
    set-hostname: hadoop-hdfs-resourcemanager-0
  type: NodePort
  sessionAffinity: None
