---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cluster2-datanode-pv-2
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /k8s-nfs-storage/zhh/bigdata-cluster2/hadoopdata/datanodedata-2
    server: 10.221.105.172
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-cluster2-hdfs-datanode-2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
