kind: Deployment
apiVersion: apps/v1
metadata:
  name: rabbitmq
  labels:
    name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rabbitmq
  template:
    metadata:
      labels:
        name: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: bitnami/rabbitmq:3.7
        env:
        - name: RABBITMQ_USERNAME
          value: 'admin'
        - name: RABBITMQ_PASSWORD
          value: 'password'
        ports:
        - containerPort: 15672
          protocol: TCP
        volumeMounts:
          - name: rabbitmq-data
            mountPath: /bitnami/rabbitmq
      volumes:
      - name: rabbitmq-data
        emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-service
  labels:
    name: rabbitmq
spec:
  type: NodePort
  ports:
  - protocol: TCP
    targetPort: 15672
    port: 15672
    name: port
  selector:
    name: rabbitmq
        