apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ APP_NAME }}-KODExplorer
  labels:
    app: {{ APP_NAME }}-KODExplorer
spec:
  template:
    metadata:
      name: {{ APP_NAME }}-KODExplorer
      labels:
        app: {{ APP_NAME }}-KODExplorer
    spec:
      containers:
      - name: {{ APP_NAME }}-KODExplorer
        image: daocloud.io/daocloud/kodexplorer
        ports:
        - containerPort: 80
        volumeMounts:
        - name: data
          mountPath: /var/www/html/data/User/admin/home/VOLUME
        resources:
          limits:
            cpu: "0.5"
            memory: "1073741824"
      volumes:
      - name: data
        hostPath:
          path: {{{home_volume}}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ APP_NAME }}-KODExplorer
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: {{ APP_NAME }}-KODExplorer
