---
kind: Service
apiVersion: v1
metadata:
  name: cluster2-namenode-standby-service
  labels:
    app: hadoop
    component: hadoop-namenode
    cluster: cluster2
spec:
  ports:
  - name: webhdfs
    protocol: TCP
    port: 50070
    targetPort: 50070
  selector:
    app: hadoop
    component: hadoop-namenode
    cluster: cluster2
    set-hostname: cluster2-hdfs-namenode-1
  type: NodePort
  sessionAffinity: None
