kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis
  labels:
    name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
      - name: redis
        image: bitnami/redis:4.0
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: 'yes'
        ports:
        - containerPort: 6379
          protocol: TCP
        volumeMounts:
          - name: redis-data
            mountPath: /bitnami/redis
      volumes:
      - name: redis-data
        emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: redis-service
  labels:
    name: redis
spec:
  type: NodePort
  ports:
  - protocol: TCP
    targetPort: 6379
    port: 6379
    name: port
  selector:
    name: redis
        