apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ APP_NAME }}-brwoser
  labels:
    app: {{ APP_NAME }}-brwoser
spec:
  template:
    metadata:
      name: {{ APP_NAME }}-brwoser
      labels:
        app: {{ APP_NAME }}-brwoser
    spec:
      containers:
      - name: {{ APP_NAME }}-brwoser
        image: daocloud.io/daocloud/etcd-browser
        ports:
          - containerPort: 8000
        env:
          - name: ETCD_HOST
            value: "127.0.0.1"
          - name: ETCD_PORT
            value: "12379"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ APP_NAME }}-brwoser
  labels:
    app: {{ APP_NAME }}-brwoser
spec:
  type: NodePort
  ports:
  - port: 8000
  selector:
    app: {{ APP_NAME }}-brwoser
