---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nodemanager-pv-2
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /k8s-nfs-storage/zhh/bigdata-demo-1/hadoopdata/nodemanagerdata-2
    server: 10.221.105.172
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-second-hdfs-nodemanager-2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
