apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ APP_NAME }}-spring-boot-admin
  labels:
    app: {{ APP_NAME }}-spring-boot-admin
spec:
  template:
    metadata:
      name: {{ APP_NAME }}-spring-boot-admin
      labels:
        app: {{ APP_NAME }}-spring-boot-admin
    spec:
      containers:
      - name: {{ APP_NAME }}-spring-boot-admin
        image: daocloud.io/grissomsh/spring-boot-admin-service:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ APP_NAME }}-spring-boot-admin
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: {{ APP_NAME }}-spring-boot-admin