apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ APP_NAME }}-service-discovery
  labels:
    app: {{ APP_NAME }}-service-discovery
spec:
  template:
    metadata:
      name: {{ APP_NAME }}-service-discovery
      labels:
        app: {{ APP_NAME }}-service-discovery
    spec:
      containers:
      - name: {{ APP_NAME }}-service-discovery
        image: daocloud.io/grissomsh/service-discovery:latest
        ports:
        - containerPort: 8761
          name: service-discovery-0
        - containerPort: 8081
          name: service-discovery-1
---
apiVersion: v1
kind: Service
metadata:
  name: {{ APP_NAME }}-service-discovery
spec:
  type: NodePort
  ports:
  - port: 8761
    name: service-discovery-0
  - port: 8081
    name: service-discovery-1
  selector:
    app: {{ APP_NAME }}-service-discovery
