---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: wekan
  name: wekan
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: wekan
    spec:
      containers:
      - env:
        - name: MONGO_URL
          value: mongodb://wekandb/wekan
        - name: ROOT_URL
          value: http://localhost:80
        image: mquandalle/wekan
        name: wekan
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: wekandb
  name: wekandb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: wekandb
    spec:
      containers:
      - args:
        - mongod
        - --smallfiles
        - --oplogSize
        - "128"
        image: mongo
        name: wekandb
        ports:
        - containerPort: 27017
        resources: {}
      restartPolicy: Always
 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: wekandb
  name: wekandb
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    service: wekandb

---    
apiVersion: v1
kind: Service
metadata:
  labels:
    service: wekan
  name: wekan
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    service: wekan
  type: "NodePort"