apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ APP_NAME }}-memcached
  labels:
    app: {{ APP_NAME }}-memcached
spec:
  template:
    metadata:
      name: {{ APP_NAME }}-memcached
      labels:
        app: {{ APP_NAME }}-memcached
    spec:
      containers:
      - name: {{ APP_NAME }}-memcached
        image: daocloud.io/memcached:latest
        ports:
        - containerPort: 11211
---
apiVersion: v1
kind: Service
metadata:
  name: {{ APP_NAME }}-memcached
spec:
  type: NodePort
  ports:
  - port: 11211
  selector:
    app: {{ APP_NAME }}-memcached
