kind: Deployment
apiVersion: apps/v1
metadata:
  name: haproxy
  labels:
    name: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: haproxy
  template:
    metadata:
      labels:
        name: haproxy
    spec:
      containers:
        - name: webapp
          image: eeacms/hello
        - name: haproxy
          image: 'eeacms/haproxy:1.8-1.1'
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 1936
              protocol: TCP
          env:
            - name: BACKENDS
              value: 'localhost'
            - name: DNS_ENABLED
              value: 'true'
            - name: LOG_LEVEL
              value: 'info'
---
kind: Service
apiVersion: v1
metadata:
  name: haproxy-service
  labels:
    name: haproxy
spec:
  ports:
    - name: haproxy
      protocol: TCP
      targetPort: 80
      port: 80
    - name: port2
      protocol: TCP
      targetPort: 1936
      port: 1936
  selector:
    name: haproxy
  type: NodePort