kind: Service
apiVersion: v1
metadata:
  name: haproxy
  labels:
    name: haproxy
  annotations:
    schemaPortname: haproxy-1/TCP
spec:
  ports:
    - name: haproxy-1
      protocol: TCP
      targetPort: 80
      port: 80
  selector:
    name: haproxy
  type: NodePort  
---
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: haproxy
  labels:
    name: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: haproxy
  template:
    metadata:
      labels:
        name: haproxy
    spec:
      containers:
        - name: haproxy
          image: 'index.tenxcloud.com/tenxcloud/haproxy:1.7'
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: PATH
              value: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
            - name: HAPROXY_MAJOR
              value: '1.7'
            - name: HAPROXY_VERSION
              value: 1.7.2
            - name: HAPROXY_MD5
              value: 7330b36f3764ebe409e9305803dc30e2
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 512Mi
          args:
            - haproxy
            - '-f'
            - /usr/local/etc/haproxy/haproxy.cfg
          command:
            - /docker-entrypoint.sh
          imagePullPolicy: IfNotPresent