---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datanode-pv-0
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /k8s-nfs-storage/zhh/bigdata-demo-1/hadoopdata/datanodedata-0
    server: 10.221.105.172
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-hadoop-hdfs-datanode-0
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
