---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: namenode-pv-standby
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /k8s-nfs-storage/zhh/bigdata-demo-1/hadoopdata/namenodedata-standby
    server: 10.221.105.172
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-hadoop-hdfs-namenode-1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
