# ownCloud with MariaDB/MySQL
#
# Access via "http://localhost:8080" (or "http://$(docker-machine ip):8080" if using docker-machine)
#
# During initial ownCloud setup, select "Storage & database" --> "Configure the database" --> "MySQL/MariaDB"
# Database user: root
# Database password: example
# Database name: pick any name
# Database host: replace "localhost" with "mysql"
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: {{ APP_NAME }}-owncloud
spec:
  ports:
    - port: 3306
  selector:
    app: {{ APP_NAME }}-owncloud
    tier: mysql
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ APP_NAME }}-owncloud-mysql
  labels:
    app: {{ APP_NAME }}-owncloud
spec:
  template:
    metadata:
      name: {{ APP_NAME }}-owncloud-mysql
      labels:
        app: {{ APP_NAME }}-owncloud
        tier: mysql
    spec:
      containers:
      - name: {{ APP_NAME }}-owncloud-mysql
        image: daocloud.io/mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ mysql_root_password }}
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      volumes:
      - name: data
        hostPath:
          path: /var/lib/mysql
---
apiVersion: v1
kind: Service
metadata:
  name: {{ APP_NAME }}-owncloud
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: {{ APP_NAME }}-owncloud
    tier: fronted
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ APP_NAME }}-owncloud
  labels:
    app: {{ APP_NAME }}-owncloud
spec:
  template:
    metadata:
      name: {{ APP_NAME }}-owncloud
      labels:
        app: {{ APP_NAME }}-owncloud
        tier: fronted
    spec:
      containers:
      - name: {{ APP_NAME }}-owncloud
        image: daocloud.io/owncloud
        ports:
        - containerPort: 80