apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ APP_NAME }}-ubuntu-desktop
  labels:
    app: {{ APP_NAME }}-ubuntu-desktop
spec:
  template:
    metadata:
      name: {{ APP_NAME }}-ubuntu-desktop
      labels:
        app: {{ APP_NAME }}-ubuntu-desktop
    spec:
      containers:
      - name: {{ APP_NAME }}-ubuntu-desktop
        image: daocloud.io/daocloud/ubuntu-desktop-lxde-vnc:latest
        ports:
        - containerPort: 6080
        resources:
          limits:
            cpu: "1.0"
            memory: "4294967296"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ APP_NAME }}-ubuntu-desktop
spec:
  type: NodePort
  ports:
  - port: 6080
  selector:
    app: {{ APP_NAME }}-ubuntu-desktop