apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ APP_NAME }}-2048
  labels:
    app: {{ APP_NAME }}-2048
spec:
  template:
    metadata:
      name: {{ APP_NAME }}-2048
      labels:
        app: {{ APP_NAME }}-2048
    spec:
      containers:
      - name: {{ APP_NAME }}-2048
        image: daocloud.io/daocloud/dao-2048:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ APP_NAME }}-2048
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: {{ APP_NAME }}-2048