kind: Service
apiVersion: v1
metadata:
  name: gitlab
  labels:
    name: gitlab
  annotations:
    schemaPortname: 'gitlab-1/TCP,gitlab-2/HTTP,gitlab-3/HTTP'
spec:
  ports:
    - name: gitlab-1
      protocol: TCP
      port: 22
      targetPort: 22
    - name: gitlab-2
      protocol: TCP
      port: 443
      targetPort: 443
    - name: gitlab-3
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    name: gitlab
  type: NodePort  
---
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: gitlab
  labels:
    name: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gitlab
  template:
    metadata:
      labels:
        name: gitlab
    spec:
      containers:
        - name: gitlab
          image: 'index.tenxcloud.com/tenxcloud/gitlab:8.8.3-ce.0'
          ports:
            - containerPort: 22
              protocol: TCP
            - containerPort: 443
              protocol: TCP
            - containerPort: 80
              protocol: TCP
          env:
            - name: PATH
              value: >-
                /opt/gitlab/embedded/bin:/opt/gitlab/bin:/assets:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            - name: TERM
              value: xterm
          resources:
            limits:
              memory: 2048Mi
            requests:
              cpu: 250m
              memory: 2048Mi
          imagePullPolicy: IfNotPresent
