kind: Deployment
apiVersion: apps/v1
metadata:
  name: gitlab-ce
  labels:
    name: gitlab-ce
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gitlab-ce
  template:
    metadata:
      labels:
        name: gitlab-ce
    spec:
      containers:
      - name: gitlab-ce
        image: gitlab/gitlab-ce:11.0.3-ce.0
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
          - name: gitlab-conf
            mountPath: /etc/gitlab
          - name: gitlab-log
            mountPath: /var/log/gitlab
          - name: gitlab-data
            mountPath: /var/opt/gitlab
      volumes:
      - name: gitlab-conf
        emptyDir: {}
      - name: gitlab-log
        emptyDir: {}
      - name: gitlab-data
        emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: gitlab-ce-service
  labels:
    name: gitlab-ce
spec:
  type: NodePort
  ports:
  - protocol: TCP
    targetPort: 80
    port: 80
    name: port80
  selector:
    name: gitlab-ce
        