apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: gitlab-ce
  name: gitlab-ce
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gitlab-ce
  template:
    metadata:
      labels:
        name: gitlab-ce
    spec:
      containers:
      - image: gitlab/gitlab-ce:11.0.3-ce.0
        name: gitlab-ce
        env:
        - name: GITLAB_OMNIBUS_CONFIG
          valueFrom:
            configMapKeyRef:
              name: gitlab-configmap
              key: omnibus-config
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 22
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/gitlab
          name: gitlab-conf
        - mountPath: /var/log/gitlab
          name: gitlab-log
        - mountPath: /var/opt/gitlab
          name: gitlab-data
      volumes:
      - name: gitlab-conf
        hostPath:
          path: /var/lib/gitlab/conf 
      - name: gitlab-log
        hostPath:
          path: /var/lib/gitlab/log 
      - name: gitlab-data
        hostPath:
          path: /var/lib/gitlab/data

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: gitlab-ce
  name: gitlab-ce-service
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
    nodePort: 30022
  selector:
    name: gitlab-ce
  type: NodePort

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: gitlab-configmap
data:
  omnibus-config: |
    external_url 'http://10.221.105.161/'
    gitlab_rails['gitlab_ssh_host'] = '10.221.105.161'
    gitlab_rails['gitlab_shell_ssh_port'] = '30022'