---
kind: Service
apiVersion: v1
metadata:
  name: hadoop-namenode-standby-service
  labels:
    app: hadoop
    component: hadoop-namenode
spec:
  ports:
  - name: webhdfs
    protocol: TCP
    port: 50070
    targetPort: 50070
  selector:
    app: hadoop
    component: hadoop-namenode
    set-hostname: hadoop-hdfs-namenode-1
  type: NodePort
  sessionAffinity: None
