---
kind: Service
apiVersion: v1
metadata:
  name: hadoop-namenode-service
  labels:
    app: hadoop
    component: hadoop-namenode
spec:
  ports:
  - name: webhdfs
    protocol: TCP
    port: 50070
    targetPort: 50070
  selector:
    app: hadoop
    component: hadoop-namenode
  type: NodePort
  sessionAffinity: None
