apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ APP_NAME }}-redis
  labels:
    app: {{ APP_NAME }}-redis
spec:
  template:
    metadata:
      name: {{ APP_NAME }}-redis
      labels:
        app: {{ APP_NAME }}-redis
    spec:
      containers:
      - name: {{ APP_NAME }}-redis
        image: daocloud.io/redis
        ports:
          - containerPort: 6379
        resources:
          limits:
            cpu: "0.5"
            memory: "2147483648"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ APP_NAME }}-redis
  labels:
    app: {{ APP_NAME }}-redis
spec:
  type: NodePort
  ports:
  - port: 6379
  selector:
    app: {{ APP_NAME }}-redis