---
kind: StatefulSet
apiVersion: apps/v1beta2
metadata:
  name: cluster2-hdfs-journalnode
  labels:
    app: hadoop
    component: hadoop-journalnode
    cluster: cluster2
  annotations:
    hadoop/version: 2.7.3
    jdk/version: jdk1.8.0_161
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hadoop
      component: hadoop-journalnode
      cluster: cluster2
  template:
    metadata:
      labels:
        app: hadoop
        component: hadoop-journalnode
        cluster: cluster2
    spec:
      volumes:
      - name: hdfs-config
        configMap:
          name: cluster2-hdfs-configmap
          defaultMode: 420
      - name: rm-config
        configMap:
          name: cluster2-rm-configmap
          defaultMode: 420
      containers:
      - name: cluster2-journalnode
        image: zhhray/hadoop:2.7.3
        command:
        - "/bin/bash"
        - "/etc/hadoop-config/bootstrap.sh"
        - "-d"
        env:
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: journal-rpc
          containerPort: 8485
          protocol: TCP   
        - name: journal-http
          containerPort: 8480
          protocol: TCP  
        resources:
          limits:
            cpu: '1'
            memory: 2Gi
          requests:
            cpu: 10m
            memory: 256Mi
        volumeMounts:
        - name: hdfs-config
          mountPath: "/tmp/hadoop/hdfs"
        - name: rm-config
          mountPath: "/tmp/hadoop/resourcemanager"
        - name: datadir
          mountPath: "/usr/local/hadoop/journaldata"
        livenessProbe:
          exec:
            command:
            - "/bin/bash"
            - "/etc/hadoop-config/healthcheck-journalnode.sh"
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - "/bin/bash"
            - "/etc/hadoop-config/healthcheck-journalnode.sh"
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3   
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      ### podAntiAffinity 描述pod被调度的策略
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: hadoop
                  component: hadoop-journalnode
                  cluster: cluster2
              topologyKey: kubernetes.io/hostname           
      schedulerName: default-scheduler
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 3Gi    
  serviceName: cluster2-journalnode-headless
  podManagementPolicy: Parallel
